//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kiliclioglumvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kilicliogluEntities : DbContext
    {
        public kilicliogluEntities()
            : base("name=kilicliogluEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<notice> notice { get; set; }
        public virtual DbSet<contact> contact { get; set; }
    }
}
